#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input().strip())
    sortedN = []
    for N_itr in range(N):
        first_multiple_input = input().rstrip().split()

        firstName = first_multiple_input[0]

        emailID = first_multiple_input[1]

        match = re.search(r"@gmail.com", emailID)  
        if match:
            sortedN.append(firstName)
    sortedN.sort()
    for i in sortedN:
        print(i)
